import { Employee } from 'src/models/employee.model';

export const emp: Employee[] = [
  {
    id: 1,
    firstname: 'Rajani',
    lastname: 'nadimpalli',
    birthdate: '1989-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: '3.png',
    category: 'IT',
  },
  {
    id: 2,
    firstname: 'srinu',
    lastname: 'nadimpalli',
    birthdate: '1979-01-21',
    gender: 'm',
    education: 'graduate',
    company: 'TSC',
    jobExperience: 1,
    salary: 1,
    profile: '9.jpg',
    category: 'Non IT',
  },
  {
    id: 3,
    firstname: 'sai',
    lastname: 'N',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-03.jpg',
    category: 'IT',
  },
  {
    id: 4,
    firstname: 'Ravi',
    lastname: 'M',
    birthdate: '1996-01-21',
    gender: 'm',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 2,
    salary: 10,
    profile: '4.jpg',
    category: 'Non IT',
  },
  {
    id: 5,
    firstname: 'sai',
    lastname: 'J',
    birthdate: '1998-01-21',
    gender: 'm',
    education: 'graduate',
    company: 'Microsoft',
    jobExperience: 4,
    salary: 45,
    profile: '7.jpg',
    category: 'IT',
  },
  {
    id: 6,
    firstname: 'balu',
    lastname: 'K',
    birthdate: '2001-01-19',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 4,
    salary: 12,
    profile: 'Profile-04.jpg',
    category: ' IT',
  },
  {
    id: 7,
    firstname: 'Ruthvik',
    lastname: 'D',
    birthdate: '1999-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'TSC',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-03.jpg',
    category: 'IT',
  },
  {
    id: 8,
    firstname: 'srinu',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-02.jpg',
    category: 'Non IT',
  },
  {
    id: 9,
    firstname: 'Rani',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-05.jpg',
    category: 'IT',
  },
  {
    id: 10,
    firstname: 'nimisha',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: '10.jpg',
    category: 'Non IT',
  },
  {
    id: 11,
    firstname: 'Rajani',
    lastname: 'nadimpalli',
    birthdate: '1989-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: '3.png',
    category: 'IT',
  },
  {
    id: 12,
    firstname: 'srinu',
    lastname: 'nadimpalli',
    birthdate: '1979-01-21',
    gender: 'm',
    education: 'graduate',
    company: 'TSC',
    jobExperience: 1,
    salary: 1,
    profile: '9.jpg',
    category: 'Non IT',
  },
  {
    id: 13,
    firstname: 'Jyothi',
    lastname: 'N',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-03.jpg',
    category: 'IT',
  },
  {
    id: 14,
    firstname: 'Ravi',
    lastname: 'M',
    birthdate: '1996-01-21',
    gender: 'm',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 2,
    salary: 10,
    profile: '4.jpg',
    category: 'Non IT',
  },
  {
    id: 15,
    firstname: 'sai',
    lastname: 'J',
    birthdate: '1998-01-21',
    gender: 'm',
    education: 'graduate',
    company: 'Microsoft',
    jobExperience: 4,
    salary: 45,
    profile: '7.jpg',
    category: 'IT',
  },
  {
    id: 16,
    firstname: 'balu',
    lastname: 'K',
    birthdate: '2001-01-19',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 4,
    salary: 12,
    profile: 'Profile-04.jpg',
    category: ' IT',
  },
  {
    id: 17,
    firstname: 'Ruthvik',
    lastname: 'D',
    birthdate: '1999-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'TSC',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-03.jpg',
    category: 'IT',
  },
  {
    id: 18,
    firstname: 'srinu',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-02.jpg',
    category: 'Non IT',
  },
  {
    id: 19,
    firstname: 'Rani',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-05.jpg',
    category: 'IT',
  },
  {
    id: 20,
    firstname: 'nimisha',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: '10.jpg',
    category: 'Non IT',
  },
  {
    id: 21,
    firstname: 'Rajani',
    lastname: 'nadimpalli',
    birthdate: '1989-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: '3.png',
    category: 'IT',
  },
  {
    id: 22,
    firstname: 'srinu',
    lastname: 'nadimpalli',
    birthdate: '1979-01-21',
    gender: 'm',
    education: 'graduate',
    company: 'TSC',
    jobExperience: 1,
    salary: 1,
    profile: '9.jpg',
    category: 'Non IT',
  },
  {
    id: 23,
    firstname: 'Jyothi',
    lastname: 'N',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-03.jpg',
    category: 'IT',
  },
  {
    id: 24,
    firstname: 'Ravi',
    lastname: 'M',
    birthdate: '1996-01-21',
    gender: 'm',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 2,
    salary: 10,
    profile: '4.jpg',
    category: 'Non IT',
  },
  {
    id: 25,
    firstname: 'sai',
    lastname: 'J',
    birthdate: '1998-01-21',
    gender: 'm',
    education: 'graduate',
    company: 'Microsoft',
    jobExperience: 4,
    salary: 45,
    profile: '7.jpg',
    category: 'IT',
  },
  {
    id: 26,
    firstname: 'balu',
    lastname: 'K',
    birthdate: '2001-01-19',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 4,
    salary: 12,
    profile: 'Profile-04.jpg',
    category: ' IT',
  },
  {
    id: 27,
    firstname: 'Ruthvik',
    lastname: 'D',
    birthdate: '1999-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'TSC',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-03.jpg',
    category: 'IT',
  },
  {
    id: 28,
    firstname: 'srinu',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-02.jpg',
    category: 'Non IT',
  },
  {
    id: 29,
    firstname: 'Rani',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: 'Profile-05.jpg',
    category: 'IT',
  },
  {
    id: 30,
    firstname: 'nimisha',
    lastname: 'nadimpalli',
    birthdate: '1996-01-21',
    gender: 'f',
    education: 'graduate',
    company: 'IBM',
    jobExperience: 1,
    salary: 1,
    profile: '10.jpg',
    category: 'Non IT',
  },
];
